kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: static-data-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: static-data-pv
